version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - datamaps-db-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: datamaps
volumes:
  datamaps-db-vol:
